### ISSUE TITLE
First rank reward

### ISSUE THREAD

**Issue by devbaraus** [zorbeytorunoglu/thebestranks#1]
The first rank isn't applying rewards, I need to run a command on the first rank to add a permission, but it doesn't work.

**Comment by zorbeytorunoglu** [comment]
If you are talking about the very first rank, which is "0", yes, it doesn't have a rewarding system as far as I remember but if you think that it would be something useful, I can add for you.

**Comment by devbaraus** [comment]
It would be quite useful to me. Cause I give a permission to players so they receive a prefix.

Right now new player receive this permission through essentialsx kit on first join, but old players I have to give one by one. Also essentials doesn't support placeholderapi, so a can't run custom commands like rng placeholder.

**Comment by zorbeytorunoglu** [comment]
Done!
