### ISSUE TITLE
More placeholders

### ISSUE THREAD

**Issue by IceGames23** [zorbeytorunoglu/thebestranks#7]
Suggestion::

- Make more placeholders for PlaceholderAPI, like requirements placeholders of the next rank, for be possible to use this placeholders in others menu plugins (ChestCommands, DeluxeMenus...).

Examples:
![image](https://user-images.githubusercontent.com/71414690/213935277-bae855f6-2d91-4c0e-93f8-21f68cf55000.png)
![image](https://user-images.githubusercontent.com/71414690/213935445-0be2103e-b335-409c-989e-0731f3482d9f.png)

**Comment by zorbeytorunoglu** [comment]
Noted

**Comment by zorbeytorunoglu** [comment]
Done.
